version: '3.8'

services:

  graylog:
    image: graylog/graylog:4.3
    restart: always
    container_name: graylog
    mem_reservation: 2g
    volumes:
      - graylog:/usr/share/graylog/data
      - ./graylog/contentpacks:/usr/share/graylog/data/contentpacks
    ports:
      # Graylog web interface and REST API
      - "9000:9000"
      # Syslog TCP
      - "1514:1514"
      # Syslog UDP
      - "1514:1514/udp"
      # GELF TCP
      - "12201:12201"
      # GELF UDP
      - "12201:12201/udp"
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_MONGODB_URI=mongodb://root:example@mongo:27017/graylogdb?authSource=admin
      - GRAYLOG_CONTENT_PACKS_AUTO_INSTALL=udp-input-graylog.json
      - GRAYLOG_CONTENT_PACKS_DIR=/usr/share/graylog/data/contentpacks
      - GRAYLOG_CONTENT_PACKS_LOADER_ENABLED=true
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - reo-network
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - reo-network

  elasticsearch:
    image: harbor.reo.ru/library/elasticsearch:7.15.2
    restart: always
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms2g -Xmx2g"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - reo-network

volumes:
  mongo:
    driver: local
  elasticsearch:
    driver: local
  graylog:
    driver: local

networks:
  reo-network:
    driver: bridge
