version: '2'
services:
  # MongoDB:
  mongodb:
    image: mongo:3
    volumes:
      - mongo_data:/data/db
  # Elasticsearch:
  elasticsearch:
    image: elasticsearch:6.8.23
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - GRAYLOG_CONTENT_PACKS_AUTO_INSTALL=udp-input-graylog.json
      - GRAYLOG_CONTENT_PACKS_DIR=data/contentpacks
      - GRAYLOG_CONTENT_PACKS_LOADER_ENABLED=true
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  # Graylog:
  graylog:
    image: graylog/graylog:4.2
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
      - ./graylog/contentpacks:/usr/share/graylog/data/contentpacks
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=daglisecret12345
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_CONTENT_PACKS_AUTO_INSTALL=udp-input-graylog.json
      - GRAYLOG_CONTENT_PACKS_DIR=/usr/share/graylog/data/contentpacks
      - GRAYLOG_CONTENT_PACKS_LOADER_ENABLED=true
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
# Volumes for persisting data
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local
